### ISSUE TITLE
Set up Jenkins/GCE VM based Prow agents

### ISSUE THREAD

**Issue by munnerz** [jetstack/test-infra#20]
In order to run tests that require a docker daemon using Prow, we need to be able to run jobs on builders with their *own kernel* with root access.

This is a potential security risk, especially given we have public projects now.

We can gate these tests so that they require approval from an org member to run (eg. `/ok-to-test`), but even then we shouldn't *really* allow different tests (and furthermore, different projects) to interfere with each other.

Prow supports a Jenkins agent, that can talk to an existing Jenkins deployment in order to run jobs. This *is* deprecated however, but still usable and working.

The alternative, which is potentially more re-usable/useful for others outside of Jetstack, is to create a way to launche VMs on GCE/somewhere, and run the build there.

This could be done through:

1) A new image in `images/` - this image would wrap around some `gcloud` hackery in order to spin up a VM, upload appropriate content to the VM, attach stderr/stdout, and run the build.

2) A new agent in Prow, that can launch GCE VMs - this would be similar to the kubernetes agent, but instead runs the jobs on GCE. This is likely more work, and won't be particularly re-usable if someone forks our repository and wants to rerun the test themselves.

I'm inclined to explore (1), provided we are okay with the cost of running these tests in GCE. As before, they would be gated by an `/ok-to-test` from an org member.

We should probably explore options for tracking spend if we are going to do this, and/or some kind of alert for 'old' VMs. The builds themselves could be run in preemptible VMs and spread across multiple zones/regions (managed by the image described in (1)).

If in future we want to provide an entire project per-build, we may need to explore deploying [boskos](https://github.com/jetstack/test-infra/tree/master/boskos) (currently used by kubernetes e2e to allocate a project-per-e2e suite)

**Comment by simonswine** [comment]
I think this is a good idea. This could even work for puppet tests around beaker.

I think its sensible to use a separate project from jetstack-build-infra for it, later we can make this spinup dynamically, if necessary.

I think the alerting work that @dippynark has done around prometheus and cloud-billing should be able to covert the not cleaned up instances after 2 days or so. If we want to have a quicker feedback loop we should export instance numbers in various clouds/projects/accounts and monitor these as well.

I think the risk is quite low to just start with some jobs and a static project. We then can see how that goes and move more stuff over for tarmak for example...

 at least export the instance counts
