### ISSUE TITLE
/test e2e v1.8, triggers the v1.7 e2e tests too

### ISSUE THREAD

**Issue by wallrj** [jetstack/test-infra#54]
I commented with `/test e2e v1.8` expecting only to run the v1.8 tests.

But the v1.7 tests seem to have been triggered too.

![screenshot from 2017-11-13 17-30-57](https://user-images.githubusercontent.com/978965/32739673-82618d8a-c898-11e7-8f63-9526a2dc185d.png)

**Comment by munnerz** [comment]
The regex that triggers jobs is here: https://github.com/jetstack/test-infra/blob/master/prow/config.yaml#L250 & here:
https://github.com/jetstack/test-infra/blob/master/prow/config.yaml#L256

Needs adjusting accordingly!

**Comment by munnerz** [comment]
Closed by #71
