### ISSUE TITLE
Builds hanging without any logs 

### ISSUE THREAD

**Issue by wallrj** [jetstack/test-infra#67]
Three recent builds have been pending for over 8h:
* https://prow.build-infra.jetstack.net/?repo=jetstack%2Fnavigator&state=pending
![screenshot-2017-11-15 prow status](https://user-images.githubusercontent.com/978965/32830380-e243969e-c9ec-11e7-919f-7dd54d46a009.png)

The results pages give 500 server failures:
![screenshot from 2017-11-15 10-09-30](https://user-images.githubusercontent.com/978965/32830444-180de266-c9ed-11e7-8ca5-52df9ab98758.png)

And there are no logs in google storage:
 *https://console.cloud.google.com/storage/browser/jetstack-logs/pr-logs/pull/jetstack_navigator/131/navigator-e2e-v1-8/85/

**Comment by munnerz** [comment]
This was due to us switching over to GCE infra. Going to close this now :)
