### ISSUE TITLE
Signs that our build infrastructure is over loaded

### ISSUE THREAD

**Issue by wallrj** [jetstack/test-infra#68]
https://jetstack-build-infra.appspot.com/build/jetstack-logs/pr-logs/pull/jetstack_navigator/130/navigator-e2e-v1-8/75/?log#log

```
W1114 23:28:06.240] + kube_service_responding test-cassandracluster-1510701676-31209 cass-cassandra-1510701676-31209-cassandra 9043
W1114 23:28:06.240] + local namespace=test-cassandracluster-1510701676-31209
W1114 23:28:06.240] + local host=cass-cassandra-1510701676-31209-cassandra
W1114 23:28:06.240] + local port=9043
W1114 23:28:06.240] + kubectl run --namespace=test-cassandracluster-1510701676-31209 kube-service-responding-10242 --stdin=true --rm --restart=Never --image alpine -- nc -w 5 -v cass-cassandra-1510701676-31209-cassandra 9043
W1114 23:28:16.363] error: failed to discover supported resources: Get https://192.168.42.162:8443/api: net/http: TLS handshake timeout
```

```
I1114 23:31:07.932] [debug] Created tunnel using local port: '40930'
I1114 23:31:07.932] 
I1114 23:31:07.932] [debug] SERVER: "localhost:40930"
I1114 23:31:07.932] 
W1114 23:31:08.246] E1114 23:31:08.245926    6980 portforward.go:331] an error occurred forwarding 40930 -> 44134: error forwarding port 44134 to pod f5bdd89f9da5116f3a6ccebb29e1c4448f06027bac37fb7029673d3f5bad1c77, uid : exit status 1: 2017/11/14 23:31:06 socat[10443.140469232314112] E connect(5, AF=2 127.0.0.1:44134, 16): Connection refused
W1114 23:31:08.247] Error: UPGRADE FAILED: transport is closing
```

In https://github.com/kubernetes/helm/issues/3140#issuecomment-344446966 @bacongobbler wrote:
> Hmm, so a connection refused error from socat when forwarding ports would be an indicator that kube-proxy is starting to fail, possibly due to exhausted infrastructure. Because the error comes straight from kube-proxy in the form of socat failing, there's not much we can do to improve the error message or in the form of retrying the connection (because the connection was already established, but the proxy cut the connection), but a PR upstream to improve the error message would probably improve the situation!
> I would check your kubernetes cluster and see why kube-proxy is starting to flap. :)

**Comment by munnerz** [comment]
We've now moved to GCE with bigger instances. We may in future enable autoscaling on the instance group if we start to see this again.
