### ISSUE TITLE
Need `helm` installed in the build container

### ISSUE THREAD

**Issue by wallrj** [jetstack/test-infra#85]
In https://github.com/jetstack/navigator/pull/165 we want to run `helm lint` in CI.
```
I1201 10:30:12.127] helm lint contrib/charts/*
I1201 10:30:12.129] Makefile:107: recipe for target 'helm_verify' failed
W1201 10:30:12.136] /bin/bash: helm: command not found
W1201 10:30:12.136] make: *** [helm_verify] Error 127
```

**Comment by munnerz** [comment]
It should be possible to install Helm here: https://github.com/jetstack/test-infra/blob/master/images/minikube/Dockerfile

You'll also need to change the image tag in the images Makefile in that same directory, and then update Prow to use this new image tag (at a few points in this file: https://github.com/jetstack/test-infra/blob/master/prow/config.yaml)
